# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


[[main]]
  name = "Postagens"
  url = "#posts"
  weight = 20

[[main]]
  name = "Projetos"
  url = "#projects"
  weight = 30

[[main]]
  name = "Publicações"
  url = "#featured"
  weight = 40

[[main]]
  name = "Cursos"
  url = "courses/"
  weight = 50

[[main]]
  name = "Contato"
  url = "#contact"
  weight = 60
  
[[main]]
  name = "Vídeos"
  url = "https://www.youtube.com/channel/UCDkLzuE5WtNF0HRzTnsj-UA"
  weight = 20
  
[[main]]
  name = "Paletras e Workshops"
  url = "#talks"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[main]]
    name = "Lattes"
    url = "http://lattes.cnpq.br/2831196588233643"
   weight = 70
